services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"  # Порт для HTTP API Elasticsearch
    volumes:
      - test_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true

  logstash:
    image: logstash:7.9.1
    container_name: logstash
    ports:
      - "5044:5044"  # Порт для входящих данных (например, от Filebeat)
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Порт для доступа к Nginx
    volumes:
      - ./nginx-logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    container_name: filebeat
    volumes:
      - ./elk-config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - elasticsearch

volumes:
  test_data:
